version: '3.6'

services:
    php-fpm:
#        image: project-php-fpm
        build: php-fpm
        volumes:
            # Time Zone and Local Time
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ${SYMFONY_APP_PATH}:/var/www
#            - logs/symfony:/var/www/symfony/app/logs
        networks:
            - project
    pgsql:
        image: postgres:alpine
        restart: always
        volumes:
            # Time Zone and Local Time
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - pgsqldata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - project

    nginx:
        build: nginx
        ports:
            - 80:80
        volumes:
            # Time Zone and Local Time
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ${SYMFONY_APP_PATH}:/var/www
#            - logs/nginx/:/var/log/nginx
        networks:
            - project
#    elasticsearch:
#        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
#        container_name: elasticsearch
#        environment:
#            - cluster.name=single-node
#            - bootstrap.memory_lock=true
#            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#        ulimits:
#            memlock:
#                soft: -1
#                hard: -1
#        volumes:
#            - elkdata:/usr/share/elasticsearch/data
#        ports:
#            - 9200:9200
#        networks:
#            - project

    tideways:
        build: ./tideways
        networks:
          - project

networks:
    project:
        driver: bridge

volumes:
    pgsqldata:
        external: false
#    elkdata:
#        driver: local
    logs:



#    nginx:
#        build: nginx
#        ports:
#            - 80:80
#        volumes_from:
#            - php
#        volumes:
#            # Time Zone and Local Time
#            - /etc/localtime:/etc/localtime:ro
#            - /etc/timezone:/etc/timezone:ro
#            - ./logs/nginx/:/var/log/nginx
#    elk:
#        image: willdurand/elk
#        ports:
#            - 81:80
#        volumes:
#            - /etc/localtime:/etc/localtime:ro
#            - /etc/timezone:/etc/timezone:ro
#
#            - ./elk/logstash:/etc/logstash
#            - ./elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx
